importação das bibliotecas

In [19]:
import pandas as pd
import numpy as np

### pandas

In [4]:
# carregamento dos data frames
df_excel = pd.read_excel("Chess.xlsx", sheet_name="Chess")
df_csv = pd.read_csv("https://raw.githubusercontent.com/FIAP/Pos_Tech_DTAT/" \
"61a634996879d5c1384af6f567e29659ad68b727/Aula%2002/Base%20de%20Dados/Tomato.csv", sep=",")

In [5]:
# leitura do df_excel usando a função head() que mostra por padrão as 5 primeiras linhas
df_excel.head()

rated    created_at  last_move_at  turns victory_status winner  \
0  False  1.504210e+17  1.504210e+17     13      outoftime  white   
1   True  1.504130e+17  1.504130e+17     16         resign  black   
2   True  1.504130e+17  1.504130e+17     61           mate  white   
3   True  1.504110e+17  1.504110e+17     61           mate  white   
4   True  1.504030e+17  1.504030e+17     95           mate  white   

  increment_code       white_id  white_rating      black_id  black_rating  \
0           15+2       bourgris          1500          a-00          1191   
1           5+10           a-00          1322     skinnerua          1261   
2           5+10         ischia          1496          a-00          1500   
3           20+0  daniamurashov          1439  adivanov2009          1454   
4           30+3      nik221107          1523  adivanov2009          1469   

  opening_eco                            opening_name  opening_ply  
0         D10        Slav Defense: Exchange Variation            5  
1         B00  Nimzowitsch Defense: Kennedy Variation            4  
2         C20   King's Pawn Game: Leonardis Variation            3  
3         D02  Queen's Pawn Game: Zukertort Variation            3  
4         C41                        Philidor Defense            5

In [6]:
# leitura do df_csv usando a função tail() que mostra por padrão as últimas 5 linhas
df_csv.tail()

Date Unit  Minimum  Maximum  Average  Market
2736  2021-05-09   Kg       10       15     12.5  Tomato
2737  2021-05-10   Kg       10       15     12.5  Tomato
2738  2021-05-11   Kg       10       15     12.5  Tomato
2739  2021-05-12   Kg       30       35     32.5  Tomato
2740  2021-05-13   Kg       35       40     37.5  Tomato

In [7]:
# usa o atributo shape para mostrar a quantidade de linhas e colunas do df_csv
df_csv.shape

(2741, 6)

In [8]:
# usa a função info para verificar o tipo de dado de cada coluna do df_excel
df_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20058 entries, 0 to 20057
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   rated           20058 non-null  bool   
 1   created_at      20058 non-null  float64
 2   last_move_at    20058 non-null  float64
 3   turns           20058 non-null  int64  
 4   victory_status  20058 non-null  object 
 5   winner          20058 non-null  object 
 6   increment_code  20058 non-null  object 
 7   white_id        20058 non-null  object 
 8   white_rating    20058 non-null  int64  
 9   black_id        20058 non-null  object 
 10  black_rating    20058 non-null  int64  
 11  opening_eco     20058 non-null  object 
 12  opening_name    20058 non-null  object 
 13  opening_ply     20058 non-null  int64  
dtypes: bool(1), float64(2), int64(4), object(7)
memory usage: 2.0+ MB


In [9]:
# usa a função describe para obter estatísticas descritivas do df_csv
df_csv.describe()

Minimum      Maximum      Average
count  2741.000000  2741.000000  2741.000000
mean     35.089748    41.281284    38.185516
std      16.648425    17.364135    16.970949
min       8.000000    12.000000    10.000000
25%      22.000000    30.000000    25.000000
50%      30.000000    38.000000    35.000000
75%      45.000000    50.000000    47.500000
max     115.000000   120.000000   117.500000

In [10]:
# usa o atributo T para transpor o resultado da função describe
df_csv.describe().T

count       mean        std   min   25%   50%   75%    max
Minimum  2741.0  35.089748  16.648425   8.0  22.0  30.0  45.0  115.0
Maximum  2741.0  41.281284  17.364135  12.0  30.0  38.0  50.0  120.0
Average  2741.0  38.185516  16.970949  10.0  25.0  35.0  47.5  117.5

In [11]:
# usa a função head para visualizarmos as colunas e posteriormente selecionarmos uma coluna específica
df_excel.head()

rated    created_at  last_move_at  turns victory_status winner  \
0  False  1.504210e+17  1.504210e+17     13      outoftime  white   
1   True  1.504130e+17  1.504130e+17     16         resign  black   
2   True  1.504130e+17  1.504130e+17     61           mate  white   
3   True  1.504110e+17  1.504110e+17     61           mate  white   
4   True  1.504030e+17  1.504030e+17     95           mate  white   

  increment_code       white_id  white_rating      black_id  black_rating  \
0           15+2       bourgris          1500          a-00          1191   
1           5+10           a-00          1322     skinnerua          1261   
2           5+10         ischia          1496          a-00          1500   
3           20+0  daniamurashov          1439  adivanov2009          1454   
4           30+3      nik221107          1523  adivanov2009          1469   

  opening_eco                            opening_name  opening_ply  
0         D10        Slav Defense: Exchange Variation            5  
1         B00  Nimzowitsch Defense: Kennedy Variation            4  
2         C20   King's Pawn Game: Leonardis Variation            3  
3         D02  Queen's Pawn Game: Zukertort Variation            3  
4         C41                        Philidor Defense            5

In [12]:
# usa a função set para verificar os valores únicos da coluna "victory_status" do df_excel
set(df_excel["victory_status"])

{'draw', 'mate', 'outoftime', 'resign'}

In [13]:
# usa a função head() para mostrar as primeiras linhas do df_csv para posteriormente criar uma nova coluna
df_csv.head()

Date Unit  Minimum  Maximum  Average  Market
0  2013-06-16   Kg       26       32     29.0  Tomato
1  2013-06-17   Kg       20       25     22.5  Tomato
2  2013-06-18   Kg       22       26     24.0  Tomato
3  2013-06-19   Kg       24       28     26.0  Tomato
4  2013-06-20   Kg       22       26     24.0  Tomato

In [14]:
# cria a função para classificar o tamanho do tomate com base na media
def categorizar_media_tomate(media):
  if media >= 40 and media <= 70:
    return "tomate medio"
  elif media < 40:
    return "tomate pequeno"
  else:
    return "tomatao"

In [15]:
# cria uma nova coluna no df usando com base a Average e a função categorizar_media_tomate em cima dessa coluna
df_csv["categoria_tomate"] = df_csv["Average"].apply(categorizar_media_tomate)

In [16]:
# visualiza o df com a nova coluna criada
df_csv.head()

Date Unit  Minimum  Maximum  Average  Market categoria_tomate
0  2013-06-16   Kg       26       32     29.0  Tomato   tomate pequeno
1  2013-06-17   Kg       20       25     22.5  Tomato   tomate pequeno
2  2013-06-18   Kg       22       26     24.0  Tomato   tomate pequeno
3  2013-06-19   Kg       24       28     26.0  Tomato   tomate pequeno
4  2013-06-20   Kg       22       26     24.0  Tomato   tomate pequeno

In [17]:
# valida quais foram os valores da coluna criada
df_csv.groupby(["categoria_tomate"]).describe()

Minimum                                                      \
                   count       mean       std   min   25%   50%   75%    max   
categoria_tomate                                                               
tomatao            149.0  75.744966  7.324666  65.0  70.0  75.0  80.0  115.0   
tomate medio       954.0  47.818658  8.203065  30.0  40.0  45.0  55.0   65.0   
tomate pequeno    1638.0  23.978022  7.175572   8.0  18.0  25.0  30.0   38.0   

                 Maximum             ...              Average             \
                   count       mean  ...   75%    max   count       mean   
categoria_tomate                     ...                                   
tomatao            149.0  82.583893  ...  85.0  120.0   149.0  79.164430   
tomate medio       954.0  55.009434  ...  60.0   75.0   954.0  51.414046   
tomate pequeno    1638.0  29.528694  ...  35.0   44.0  1638.0  26.753358   

                                                           
                       std   min   25%   50%   75%    max  
categoria_tomate                                           
tomatao           7.367396  70.5  75.0  77.5  82.5  117.5  
tomate medio      8.272792  40.0  45.0  50.0  57.5   70.0  
tomate pequeno    7.191735  10.0  21.5  27.5  32.5   39.5  

[3 rows x 24 columns]

In [ ]:
# cria a variavel filtro que irá checar a coluna average (média) do dataframe pegando o que for menor que 40 e em seguida, usa o atributo
# loc que irá de fato filtrar o df
filtro = df_csv["Average"] < 40
df_csv.loc[filtro]

Date Unit  Minimum  Maximum  Average  Market categoria_tomate
0     2013-06-16   Kg       26       32     29.0  Tomato   tomate pequeno
1     2013-06-17   Kg       20       25     22.5  Tomato   tomate pequeno
2     2013-06-18   Kg       22       26     24.0  Tomato   tomate pequeno
3     2013-06-19   Kg       24       28     26.0  Tomato   tomate pequeno
4     2013-06-20   Kg       22       26     24.0  Tomato   tomate pequeno
...          ...  ...      ...      ...      ...     ...              ...
2736  2021-05-09   Kg       10       15     12.5  Tomato   tomate pequeno
2737  2021-05-10   Kg       10       15     12.5  Tomato   tomate pequeno
2738  2021-05-11   Kg       10       15     12.5  Tomato   tomate pequeno
2739  2021-05-12   Kg       30       35     32.5  Tomato   tomate pequeno
2740  2021-05-13   Kg       35       40     37.5  Tomato   tomate pequeno

[1638 rows x 7 columns]

### numpy

In [20]:
# cria a variavel que recebe um array usando a função array do numpy
arr_lista = np.array([1, 2, 3, 4 , 5, 6, 7, 8])

In [22]:
print(arr_lista)

[1 2 3 4 5 6 7 8]


In [ ]:
# cria a variavel que recebe array e usa a função zeros do numpy para definir os valores como 0 e passa a quantidade de linhas e colunas
arr_zeros = np.zeros((4, 6))
print(arr_zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
# cria a variavel que recebe um array de número 1 usando a função ones do numpy e passa a quantidade linhas e colunas do array
arr_ones = np.ones((3, 4))
print(arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [30]:
# cria a variavel que recebe valores aleatórios através da função random
arr_random = np.random.rand(3, 4)
print(arr_random)

[[0.62021184 0.1393822  0.53057851 0.60153153]
 [0.67541699 0.70786569 0.4149709  0.70451509]
 [0.90806506 0.33890864 0.25346516 0.99539516]]


In [ ]:
# o atributo shape também pode ser usado em um array, para trazer a dimensão do array
print(arr_random.shape)

(3, 4)


In [ ]:
# altera o formato do array arr_random usando a função reshape que é parecida com o T
arr_random_reshape = arr_random.reshape((4, 3))
print(arr_random_reshape)

[[0.62021184 0.1393822  0.53057851]
 [0.60153153 0.67541699 0.70786569]
 [0.4149709  0.70451509 0.90806506]
 [0.33890864 0.25346516 0.99539516]]


In [ ]:
# cria arrays separados para depois concatenar todos
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

In [40]:
arr1

array([[1, 2],
       [3, 4]])

In [44]:
arr4 = np.concatenate((arr1, arr2, arr3), axis=1)
print(arr4)

[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


In [48]:
# usa a função split do numpy para separar o array que foi concatenado
arr4_split = np.split(arr4, 2)
print(arr4_split)

[array([[ 1,  2,  5,  6,  9, 10]]), array([[ 3,  4,  7,  8, 11, 12]])]


In [52]:
# usa a função transpose do numpy para inverter as linhas pelas colunas
arr4_transpose = np.transpose(arr4)
print(arr4_transpose)

[[ 1  3]
 [ 2  4]
 [ 5  7]
 [ 6  8]
 [ 9 11]
 [10 12]]


In [54]:
# usa uma segunda forma para transpor o array, usando o T do python, voltando a forma que era antes
arr4_revertido = arr4_transpose.T
print(arr4_revertido)

[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


In [56]:
arr_a = np.array([1, 7, 27])
arr_b = np.array([1, 5, 1])

In [ ]:
# faz a soma de dois arrays usando a função add do numpy
arr_a_b = np.add(arr_a, arr_b)
arr_a_b

array([ 2, 12, 28])

In [62]:
# faz a soma de dois arrays usando a função add do numpy
arr_sub_a_b = np.subtract(arr_a, arr_b)
arr_sub_a_b

array([ 0,  2, 26])