In [1]:
import scipy
from scipy import stats
import numpy as np

In [5]:
# criação dos dados que serão utilizados
matriz = np.array([[8,0,3,4,6], [5,6,1,8,9], [8,0,0,5,10]])
novoUser = [8,0,2,3,0]
nao_assistidos = [0,1,0,0,1]
print(matriz)

nomeFilmes = ['Round 6', 'A Invocação do Mal', '9 Desconhecidos', 'You', 'La Casa de Papel']

[[ 8  0  3  4  6]
 [ 5  6  1  8  9]
 [ 8  0  0  5 10]]


In [6]:
#criando um vetor com 3 posições e preenchendo com zero (vamos colocar os valores da similaridade entre o novoUser e cada outro)

similarity = [0] * 3
print(matriz[0][0])
print(matriz[1][0])
print(matriz[1, :])

# para cada usuário no sistema...
for i in range (0, 3):
  # vamos pegar os dados do usuário
  temp = matriz[i,:]

  print(i, temp)
  # queremos apenas comparar os dados que o novo user assistiu (ou seja, que o novo user seja != 0)
  tempUser = [t for n, t in zip(novoUser, temp) if n != 0]
  tempNovoUser = [n for n in novoUser if n != 0]
  
  # para verificar o processo
  print ('user: ', i)
  print(tempUser, tempNovoUser)

  #vamos usar a biblioteca scipy.stats que já calcula o pearson
  similarity[i] = scipy.stats.pearsonr(tempUser, tempNovoUser)[0]
  
print()
print(similarity)

8
5
[5 6 1 8 9]
0 [8 0 3 4 6]
user:  0
[8, 3, 4] [8, 2, 3]
1 [5 6 1 8 9]
user:  1
[5, 1, 8] [8, 2, 3]
2 [ 8  0  0  5 10]
user:  2
[8, 0, 5] [8, 2, 3]

[0.9994237971287664, 0.23621543814299711, 0.8723686098443353]
