> álgebra linear -> x + 2 = 5 -> x = 3 ... serve para resolver sistemas de equações lineares

> x + y = 10 -> 0 + y = 10 --------- (0,10), (2,8) ... infinitas soluções, conhecida como equação diofantina

In [1]:
# principais bibliotecas para trabalhar com algebra
import numpy as np
import scipy as sc
import sympy as sy

In [2]:
# escalar, vetor e matriz
# escalar é a mesma coisa que número, em algebra linear, tamém é conhecido como um tensor de ordem 0
x = 2

In [3]:
type(x)

int

In [4]:
# vetor escalar
x2 = np.array([1, 2, 3])

In [5]:
print(x2)

[1 2 3]


In [6]:
# vetor de vetores, matriz
x3 = np.array([[1], [2], [3]])

In [7]:
print(x2, "\n\n", x3)

[1 2 3] 

 [[1]
 [2]
 [3]]


In [8]:
# matriz tradicional
x4 = np.array([[1,2,3], [1,2,3], [1,2,3]])

In [9]:
print(x4)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [10]:
import pandas as pd

In [11]:
lista = np.array([1,2,3,4,5])

df = pd.DataFrame({'coluna 1': lista, 'coluna 2':lista})

In [12]:
df

coluna 1  coluna 2
0         1         1
1         2         2
2         3         3
3         4         4
4         5         5

In [13]:
lista[1:]

array([2, 3, 4, 5])